create table carts (id bigint generated by default as identity, total numeric(19,2), primary key (id));
create table carts_items (cart_id bigint not null, items_id bigint not null);
create table items (id bigint generated by default as identity, description varchar(255) not null, name varchar(255) not null, price numeric(19,2) not null, primary key (id));
create table user_order (id bigint generated by default as identity, total numeric(19,2), user_id bigint not null, primary key (id));
create table user_order_items (user_order_id bigint not null, items_id bigint not null);
create table users (id bigint generated by default as identity, password varchar(255) not null, username varchar(255) not null, cart_id bigint, primary key (id));
